global:
  scrape_interval:     30s # El intervalo en el que se traerá las métricas
  evaluation_interval: 30s # Evaluará las reglas cada 30 segundos, por defecto es cada minuto
  
scrape_configs:

  - job_name: node_exporter
    static_configs:
    - targets: ['node_exporter:9100']

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
    - targets:
      - cadvisor:8080
  
  - job_name: 'mit-api-core'
    dns_sd_configs:
    - names:
      - 'mit-api-core'
      type: 'A'
      port: 6565
    metrics_path: '/actuator/prometheus'

