---
- hosts: selenium_hub, selenium_nodes, selenium_nodes2
  become: true
  tasks:
    - name: Enable IP forwarding persistently
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ip_forward = 1"
        insertafter: EOF


